import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

// TODO: Replace the placeholder values below with real credentials generated by
// `flutterfire configure`. Keeping the structure in place allows the rest of
// the app to compile before the actual config file is generated.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        return _macos;
      case TargetPlatform.windows:
        return _windows;
      case TargetPlatform.linux:
        return _linux;
      default:
        throw UnsupportedError(
          "DefaultFirebaseOptions are not configured for this platform. "
          "Run `flutterfire configure` or edit firebase_options.dart.",
        );
    }
  }

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: "ANDROID_API_KEY",
    appId: "ANDROID_APP_ID",
    messagingSenderId: "ANDROID_SENDER_ID",
    projectId: "PROJECT_ID",
    storageBucket: "PROJECT_ID.appspot.com",
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: "IOS_API_KEY",
    appId: "IOS_APP_ID",
    messagingSenderId: "IOS_SENDER_ID",
    projectId: "PROJECT_ID",
    iosClientId: "IOS_CLIENT_ID",
    iosBundleId: "com.example.stemly",
  );

  static const FirebaseOptions _macos = FirebaseOptions(
    apiKey: "MACOS_API_KEY",
    appId: "MACOS_APP_ID",
    messagingSenderId: "MACOS_SENDER_ID",
    projectId: "PROJECT_ID",
    iosClientId: "MACOS_CLIENT_ID",
    iosBundleId: "com.example.stemly",
  );

  static const FirebaseOptions _windows = FirebaseOptions(
    apiKey: "WINDOWS_API_KEY",
    appId: "WINDOWS_APP_ID",
    messagingSenderId: "WINDOWS_SENDER_ID",
    projectId: "PROJECT_ID",
  );

  static const FirebaseOptions _linux = FirebaseOptions(
    apiKey: "LINUX_API_KEY",
    appId: "LINUX_APP_ID",
    messagingSenderId: "LINUX_SENDER_ID",
    projectId: "PROJECT_ID",
  );
}

