// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVRs-EDLulhbsbg8nZDkr7kxuGmyk-5QQ',
    appId: '1:75140432972:web:abb60f9a3fd960cea960e9',
    messagingSenderId: '75140432972',
    projectId: 'stemly-929a6',
    authDomain: 'stemly-929a6.firebaseapp.com',
    storageBucket: 'stemly-929a6.firebasestorage.app',
    measurementId: 'G-RGELSDH9VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNoxzV5V65plojiKrGprlt4S3BOgxHksQ',
    appId: '1:75140432972:android:0c3cef77d2dc0fb1a960e9',
    messagingSenderId: '75140432972',
    projectId: 'stemly-929a6',
    storageBucket: 'stemly-929a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy22m9tzRzFoEN-hi_xPkEtuk8srmqN24',
    appId: '1:75140432972:ios:a5ccfa60db07597ba960e9',
    messagingSenderId: '75140432972',
    projectId: 'stemly-929a6',
    storageBucket: 'stemly-929a6.firebasestorage.app',
    iosBundleId: 'com.example.stemlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy22m9tzRzFoEN-hi_xPkEtuk8srmqN24',
    appId: '1:75140432972:ios:a5ccfa60db07597ba960e9',
    messagingSenderId: '75140432972',
    projectId: 'stemly-929a6',
    storageBucket: 'stemly-929a6.firebasestorage.app',
    iosBundleId: 'com.example.stemlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVRs-EDLulhbsbg8nZDkr7kxuGmyk-5QQ',
    appId: '1:75140432972:web:544b20c458a5828da960e9',
    messagingSenderId: '75140432972',
    projectId: 'stemly-929a6',
    authDomain: 'stemly-929a6.firebaseapp.com',
    storageBucket: 'stemly-929a6.firebasestorage.app',
    measurementId: 'G-RB5W9CD1G6',
  );

}